PUT http://localhost:9080/jakarta/api/v1/organisers
Content-Type: application/json

{
  "organiserName": "organiser",
  "password": "password"
}

### Get all the organisers
GET http://localhost:9080/jakarta/api/v1/organisers

### All events (non-auth)
GET http://localhost:9080/jakarta/api/v1/events

### All events (wrong-auth)
GET http://localhost:9080/jakarta/api/v1/events
Authorization: Basic dNXlcjpwYXNzd29yZA==

### All events (auth)
GET http://localhost:9080/jakarta/api/v1/events
Authorization: Basic b3JnYW5pc2VyOnBhc3N3b3Jk